### ISSUE TITLE
Handle data which is not covered by integer number of tiles in compress_hdu and decompress_hdu

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/astropy#25]
At the moment, compress_hdu and decompress_hdu assume the data is a multiple number of tiles but we should generalize this to support any data/tile shape.

**Comment by Cadair** [comment]
@astrofrog We can close this no?

**Comment by astrofrog** [comment]
Yep! The best part about this is that due to the way numpy deals with slices this required no special treatment!
