### ISSUE TITLE
Add support for pixel masking/null mask

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/astropy#34]
We should make sure our test suite includes data where a null pixel data mask is required (I think data with the BLANK/ZBLANK keyword defined). In this case we should determine a null pixel mask and compress it using the ``ZMASKCMP`` algorithm then store it in the ``NULL_PIXEL_MASK `` column of the binary table. See section 10.2.2 in the FITS standard for more details.

**Comment by astrofrog** [comment]
I think https://github.com/aperiosoftware/astropy/pull/43 might be sufficient. CFITSIO doesn't have any reference to NULL_PIXEL_MASK so it might not actually ever be needed/used in practice.

**Comment by Cadair** [comment]
we can always open an issue for NULL_PIXEL_MASK and keep it as a future todo?

**Comment by astrofrog** [comment]
Sure sounds good, but I'm not sure any other packages would be able to read such files :laughing:

**Comment by Cadair** [comment]
Astropy's Unique Selling Point at last :D

**Comment by astrofrog** [comment]
Closing as ZBLANK is implemented and the other parts are not needed as not even implemented in CFITSIO. I'll open an issue for those parts but we'll likely never do them.
